server:
  port: 1024
spring:
  application:
    name: AnimeFlow-Service
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
bangumi:
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}
  redirect_uri: ${REDIRECT_URI}
